FROM python:3.11-slim

WORKDIR /app

# Сначала копируем зависимости, чтобы их кешировать
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --find-links https://download.pytorch.org/whl/cpu/torch_stable.html -r requirements.txt


# Скачиваем NLTK данные один раз
RUN python -m nltk.downloader punkt stopwords

# Теперь копируем остальной код
COPY . /app

CMD ["python", "bot.py"]
